spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5433/public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# REST API定義情報
server.port=8088
api.endpoint.name=/keitaro
