# application.properties
myapp.cors.allowed-origins=http://localhost:4200

spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5433/public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis 設定
mybatis.mapper-locations=classpath:com/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# REST API定義情報
server.port=8080