# application.properties
myapp.cors.allowed-origins=http://localhost:4200

spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5433/public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis 設定
# mapper XML は classpath の com/kitafw/**/mapper/**/*.xml を参照するようにする
mybatis.mapper-locations=classpath:com/kitafw/**/mapper/**/*.xml
# Java の resultType/resultMap 用のエイリアスやドメインクラスをまとめるパッケージ
mybatis.type-aliases-package=com.kitafw.demo.controller.core.mapper.parameter
mybatis.configuration.map-underscore-to-camel-case=true

# REST API定義情報
server.port=8080